<?php

use Drupal\Core\Routing\RouteMatchInterface;
/**
* Implements hook_form_alter().
*/

function first_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
 if($form_id='user_login_form'){
    $form['#title'] = t('Login w info');
    $form['name']['#title'] = t('Just insert username');
 }        
}

// the form_id is found from the login form by inspecting, however change dash(-) in name to underscore(_)

/**
* Implements hook_preprocess_page().
*/

function first_module_preprocess_page(&$variables){
    $variables['first_module_variable']='My first D10 module';
}

/**
* Implements hook_help().
*/

function first_module_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.first_module':
        $output = '';
        $output .= '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('This is an first custom module.') . '</p>';
        return $output;
      default:
    }
  }